// Product Data Structure (for Firestore)
// Collection: 'products'
// Document ID: auto-generated by Firestore or a unique product identifier

/*
  A product document structure:
  {
    // Required fields
    name: "String", (e.g., "Snake Plant")
    price: "Number", (e.g., 15.99)
    category: "String", (One of: "Plants", "Summer Plants", "Winter Plants", "Seeds", "Adeniums", "Rain-Lillies", "Others")
    description: "String", (Detailed description of the product)
    
    // Optional fields
    scientificName: "String", (e.g., "Sansevieria trifasciata")
    stockQuantity: "Number", (e.g., 50)
    imageUrls: ["String"], // Array of URLs for multiple images
    careInstructions: {
      light: "String", (e.g., "Bright, indirect light")
      water: "String", (e.g., "Water thoroughly when soil is dry")
      soil: "String", (e.g., "Well-draining potting mix")
    },
    addedAt: "Timestamp", (Firestore server timestamp, for when the product was added)
    updatedAt: "Timestamp" (Firestore server timestamp, for when the product was last updated)
  }
*/

// We might add validation functions here later if needed.
// For example:
// const validateProductData = (data) => { ... return { isValid: true/false, errors: {} }; }

module.exports = {}; // Can export validation functions or constants if any
